version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: thinhlv/laravel-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: DOCKER_IMAGE
          tag: DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: DOCKER_IMAGE
          tag: DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - run:
workflows:
  my-pipeline:
    jobs:
      - build-and-push
