version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  php: circleci/php@1.1.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: thinhlam159/laravel-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  install_composer_packages:
    executor: php/default
    steps:
      - checkout
      - php/install-composer:
          install-version: 1.10.16
      - php/install-packages
workflows:
  my-pipeline:
    jobs:
      - install_composer_packages
      - php/test
      - build-and-push:
          requires:
            - php/test
