version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: thinhlam159/laravel-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  test:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP dependencies
          command: composer install --no-interaction --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - vendor
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package.json" }}
            - v1-npm-
      - run:
          name: Install Node dependencies
          command: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Set up database
          command: php artisan migrate --env=testing
      - run:
          name: Run PHPUnit tests
          command: ./vendor/bin/phpunit

workflows:
  my-pipeline:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
