name: PHP check standard code
on:
  push:
    branches:
      - main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
  php-quality-control:
    runs-on: ubuntu-latest
    container: lyni/phpqa:8.1
    steps:
      - name: GIT Checkout
        uses: actions/checkout@v2
      - name: Composer Install
        run: composer i -n
      - name: PHP Stan
        run: phpstan analyse core modules --level 0
      - name: PHP Magic Number
        run: phpmnd core modules --ignore-numbers=2,-1,200,401,403,404,405,422,500 --ignore-funcs=round,sleep --exclude=tests --progress --extensions=default_parameter,-return,argument
      - name: PHP Copy/Paste Detector
        run: phpcpd core modules
      - name: PHP Security
        run: local-php-security-checker
      - name: PHP CS
        run: phpcs --standard=PSR12 core modules
